// get all music constants
export const GET_FAVORITE_MUSIC = 'GET_FAVORITE_MUSIC'
export const GET_FAVORITE_MUSIC_SUCCESS = 'GET_FAVORITE_MUSIC_SUCCESS'
export const GET_FAVORITE_MUSIC_FAILED = 'GET_FAVORITE_MUSIC_FAILED'