// get all featured music constants
export const GET_ALL_FEATURED_MUSIC = 'GET_ALL_FEATURED_MUSIC'
export const GET_ALL_FEATURED_MUSIC_SUCCESS = 'GET_ALL_FEATURED_MUSIC_SUCCESS'
export const GET_ALL_FEATURED_MUSIC_FAILED = 'GET_ALL_FEATURED_MUSIC_FAILED'